package interfaces

import (
	. "github.com/dave/jennifer/jen"
	"github.com/pschichtel/auto-marshal/pkg/api"
	"github.com/pschichtel/auto-marshal/pkg/api/structs"
	"go/types"
)

func GenerateCode(sourceFile string, interfaceObject *types.Object, implementations []*types.TypeName, jsonTypeTagName string) error {
	file := generateFile(interfaceObject, implementations, jsonTypeTagName)
	return file.Save(api.DeriveOutputFileName(sourceFile, interfaceObject))
}

func generateFile(interfaceObject *types.Object, implementations []*types.TypeName, jsonTypeTagName string) *File {
	typeTagFieldName := "JsonTypeTag" // TODO derive a unique name from the implementations

	file := api.CreateJenFile(interfaceObject)
	file.PackageComment("// Code generated by github.com/pschichtel/auto-marshal! DO NOT EDIT.")

	generateEncoderFunction(file, interfaceObject, typeTagFieldName, implementations)

	return file
}

func mapSlice[I any, O any](slice []I, f func(I) O) []O {
	var output []O
	for _, value := range slice {
		output = append(output, f(value))
	}
	return output
}

func generateEncoderFunction(file *File, interfaceObject *types.Object, typeTagFieldName string, implementations []*types.TypeName) {
	actualName := "actual"
	cases := mapSlice(implementations, func(i *types.TypeName) Code {
		return Case(Id(i.Name())).Block(generateMarshalSwitchCase(i, actualName)...)
	})
	cases = append(cases, Default().Block(Return(Qual("github.com/pschichtel/auto-marshal/pkg/api/encoder", "JsonEncodingError").Call(Lit("Unknown type: ").Op("+").Qual("reflect", "TypeOf").Call(Id(actualName)).Dot("Name").Call()))))
	interfaceName := (*interfaceObject).Name()
	file.Func().Id(api.EncoderFunctionNameForNamedType(interfaceName)).Params(
		api.EncoderFunctionParams(interfaceName)...,
	).Params(Error()).Block(
		If(Id(api.ValueVariableName).Op("==").Nil()).Block(
			Id(api.WriterVariableName).Dot("RawString").Call(Lit("null")),
			Return(Nil()),
		),
		Id(api.WriterVariableName).Dot("RawString").Call(Lit("{")),
		Id(api.WriterVariableName).Dot("String").Call(Lit(typeTagFieldName)),
		Id(api.WriterVariableName).Dot("RawString").Call(Lit(":")),
		Switch(Id(actualName).Op(":=").Parens(Op("*").Id(api.ValueVariableName)).Assert(Type())).Block(cases...),
		Id(api.WriterVariableName).Dot("RawString").Call(Lit("}")),
		Return(Nil()),
	).Line()
}

func generateMarshalSwitchCase(implementation *types.TypeName, actualName string) []Code {
	implName := implementation.Name()
	return []Code{
		Id(api.WriterVariableName).Dot("String").Call(Lit(implName)),
		Err().Op(":=").Id(structs.StructFieldEncoderFunctionNameForNamedType(implName)).Call(Op("&").Id(actualName), Id(api.WriterVariableName), False()),
		If(Err().Op("!=").Nil()).Block(
			Return(Err()),
		),
	}
}

func marshalAuxStructName(interfaceObject *types.Object, implementation *types.TypeName) string {
	return "aux" + (*interfaceObject).Name() + "TaggedJson" + implementation.Name()
}
